#!/bin/env sh

mkdir -p ./content
mkdir -p ./ssl
mkdir -p ./logs

touch logs/gemini.txt
touch logs/gopher.txt
touch logs/finger.txt
touch logs/http.txt
touch logs/runner.txt

echo "Hello, world!" > content/index.gmi

echo "Create an SSL certificate for your new server:"

openssl req -x509 -nodes -newkey rsa:4096 \
    -keyout "./ssl/gemini.key" \
    -out "./ssl/gemini.cert" \
    -days 36500

echo "You must create HTTPS certificates separately, using a tool like certbot. Because of this, HTTPS is disabled by default - to reenabled it, go to protocols/http.nim and change useHttps to 'true'." | fmt
